# Generated by Django 4.2.3 on 2024-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherModel',
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
