# Generated by Django 4.2.13 on 2024-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='feedback_files/')),
            ],
        ),
    ]
