# Generated by Django 4.2.4 on 2024-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
