# Generated by Django 5.0.6 on 2024-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0002_user_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
