# Generated by Django 4.2.13 on 2024-05-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='cv_files/')),
                ('cover_letter', models.FileField(upload_to='cover_letter_files/')),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
