# Generated by Django 5.0.6 on 2024-05-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0002_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='start_date',
        ),
    ]
