# Generated by Django 5.0.6 on 2024-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0003_booking_adults_booking_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
