# Generated by Django 4.2.3 on 2024-04-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CinemaHall',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
