# Generated by Django 4.2.4 on 2024-05-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0003_user_is_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_first_login',
        ),
    ]
