# Generated by Django 4.2.3 on 2024-04-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WatchIt', '0004_remove_seat_hall_delete_booking_delete_cinemahall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cinema_Type', models.CharField(max_length=100, unique=True)),
                ('numSeats', models.IntegerField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_label', models.CharField(max_length=100)),
                ('Seat_avail', models.BooleanField(default=True)),
                ('Rows', models.IntegerField(max_length=100)),
                ('Cols', models.IntegerField(max_length=100)),
                ('CinemaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WatchIt.cinemahall')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingLabel', models.CharField(max_length=1000, unique=True)),
                ('CinemaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WatchIt.cinemahall')),
            ],
        ),
    ]
