# Generated by Django 4.2.3 on 2024-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='numSeats',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='Cols',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='Rows',
            field=models.IntegerField(),
        ),
    ]
