# Generated by Django 4.2.3 on 2024-04-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0006_alter_cinemahall_numseats_alter_theatre_cols_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='Seat_avail',
            new_name='Availability',
        ),
    ]
