# Generated by Django 5.0.6 on 2024-05-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0007_cancellationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancellationRequest',
        ),
    ]
