# Generated by Django 5.0.6 on 2024-05-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0004_remove_user_is_first_login'),
        ('WatchIt', '0008_delete_cancellationrequest'),
    ]

    operations = [
    ]
