# Generated by Django 4.2.3 on 2024-04-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0008_remove_theatre_seat_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='Rows',
            field=models.CharField(),
        ),
    ]
