# Generated by Django 4.2.3 on 2024-04-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0009_alter_theatre_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_label', models.CharField(blank=True, max_length=3, null=True)),
                ('availability', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='CinemaID',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bookingLabel',
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='Cinema_Type',
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='numSeats',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_label',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='num_cols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='num_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.AddField(
            model_name='seat',
            name='cinema_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='WatchIt.cinemahall'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='WatchIt.seat'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='cinema_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
