# Generated by Django 4.2.4 on 2024-04-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0010_seat_remove_booking_cinemaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_Name', models.CharField(null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
