# Generated by Django 4.2.3 on 2024-04-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0013_payment_detail_cinema_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='movie_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviepayments', to='WatchIt.movies'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='Payment_detail',
        ),
    ]
