# Generated by Django 5.0.4 on 2024-04-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0013_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
