# Generated by Django 4.2.3 on 2024-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0014_booking_movie_title_booking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_tickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_tickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
