# Generated by Django 5.0.4 on 2024-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0015_remove_movie_category_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='tags',
        ),
    ]
