# Generated by Django 4.2.3 on 2024-04-23 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0016_remove_booking_adult_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cinema_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='WatchIt.cinemahall'),
        ),
    ]
