# Generated by Django 4.2.3 on 2024-04-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0016_rename_category_movie_tags'),
        ('WatchIt', '0017_booking_cinema_hall'),
    ]

    operations = [
    ]
