# Generated by Django 4.2.3 on 2024-04-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0018_merge_20240424_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_label',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='WatchIt.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ageRating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('starring', models.TextField(blank=True, help_text='Coma-separated list of main actors', null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('ageRating', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
                ('tags', models.ManyToManyField(related_name='movies', to='WatchIt.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviepayments', to='WatchIt.movies'),
        ),
    ]
