# Generated by Django 4.2.3 on 2024-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0020_remove_cinemahall_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='WatchIt.tag'),
        ),
    ]
