# Generated by Django 4.2.3 on 2024-04-25 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0021_remove_movie_category_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviepayments', to='WatchIt.movie'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
