# Generated by Django 4.2.3 on 2024-04-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0024_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cinemaHall',
        ),
    ]
