# Generated by Django 4.2.3 on 2024-04-28 21:38

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0026_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
