# Generated by Django 4.2.3 on 2024-05-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0029_alter_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie_title',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='WatchIt.movie'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='seats_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='WatchIt.seat'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='cinema_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='WatchIt.cinemahall'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='WatchIt.movie'),
        ),
    ]
