# Generated by Django 4.2.3 on 2024-05-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0031_remove_booking_movie_remove_showtime_seats_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='cinema_hall',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='WatchIt.movie'),
        ),
        migrations.AddField(
            model_name='seat',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='WatchIt.showtime'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='seats_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='WatchIt.seat'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.TextField(blank=True, help_text='Comma-separated list of main actors', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='movies', to='WatchIt.tag'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seat',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_label',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='WatchIt.movie'),
        ),
    ]
