# Generated by Django 4.2.3 on 2024-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0032_remove_booking_movie_title_remove_seat_cinema_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_label',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
