# Generated by Django 4.2.3 on 2024-05-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0034_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
