# Generated by Django 5.0.6 on 2024-05-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0036_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='WatchIt.showtime'),
        ),
    ]
