# Generated by Django 5.0.6 on 2024-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0038_booking_num_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
