# Generated by Django 5.0.6 on 2024-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0039_booking_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
    ]
