# Generated by Django 4.2.13 on 2024-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0041_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
