# Generated by Django 4.2.13 on 2024-05-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0042_booking_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
