# Generated by Django 5.0.6 on 2024-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchIt', '0043_booking_card_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
